test: Clean-up remaining code from compat tests
Amends commit 43138ee.

Fixes:
```
E   ImportError: cannot import name 'DockerComposeCompatibilitySetup' from 'testutils.infra.container_manager.docker_compose_manager' (/home/lluis/northern.work/integration/testutils/infra/container_manager/docker_compose_manager.py)
```

Ticket: QA-683

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit e0bb78c9ccbb5c5c76f949ccffb338655266df0e)