chore: Revert "fix(tests): bound apt-get calls in test_in_poor_network_environment"
The commit message states that it depends on mender-testkit==0.1.3, but
it's not released so tests fail with
`TypeError: Connection.run() got an unexpected keyword argument 'timeout'`

This reverts commit 7761c90bf18b67571b5ce7475e4c8bb7fc86a1ff.