Add auditlogs dockerfile to "docker only" files list.
Otherwise filter_docker_compose_files_list method will fail when parsing
yaml files from integration versions with this component.

Without the fix, any use of `--integration-versions-including` in this
branch will fail with:

```
Exception: More than one container is using the image name 'auditlogs'.
The tool currently does not support this.
```

Related to master commit 223f4c77a0d72636be7c934e9bd63c5e7419216f.

Changelog: None

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>