MEN-2985 how could have this worked?
time="2019-12-28T01:06:13Z" level=info msg="DB migrated to version 1.2.2" db=deployment_service file=migrator_simple.go func="migrate.(*SimpleMigrator).Apply" line=140
RequestError: send request failed
caused by: Put https://localhost:9000/mender-artifact-storage: dial tcp 127.0.0.1:9000: connect: connection refused
bash-5.0# docker ps | grep deployments
eeb844c40743        mendersoftware/deployments:pr                         "/entrypoint.sh --co…"   2 hours ago         Restarting (4) 31 seconds ago                            mender2971309_mender-deployments_1

Changelog: none
Signed-off-by: Peter Grzybowski <peter@northern.tech>